import os
from argparse import ArgumentParser
from my_prompts import INITIAL_PROPOSAL, OBJ_VERIFICATION, OBJ_REFINEMENT, PART_VERIFICATION, PART_REFINEMENT
from my_utils import plot_bounding_boxes
from concurrent.futures import ThreadPoolExecutor, as_completed

# Packages used for Qwen2.5-VL
import io
import ast
import json
import torch
import random
import xml.etree.ElementTree as ET
from tqdm import tqdm
from PIL import ImageColor
from PIL import Image, ImageDraw, ImageFont
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info

# Packages used for GPT4o api
import sys
import cv2
import time
import base64
import argparse
import numpy as np
from openai import AzureOpenAI
import matplotlib.pyplot as plt

def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--data", type=str, default="/home/jibokai/affordance/LISA/downsampled_affordance_dataset.json", help="Path to the COT dataset")
    parser.add_argument("--actor", type=str, default="/data/public/modelzoo/Qwen2.5-VL-72B-Instruct", help="HF or local path of the VLM")
    parser.add_argument("--verifier", type=str, default="GPT4o", help="GPT4o or the actor itself")
    parser.add_argument("--logdir", type=str, default="cot_logs", help="Log directory")
    parser.add_argument("--exp-name", type=str, default="72B", help="Experiment name")
    parser.add_argument("--max-trails", type=int, default=5, help="Max number of trails")
    return parser.parse_args()

def build_actor(actor_path):
    """
    Build Qwen2.5-VL instance (7B/72B), and return the actor and processor
    """
    actor = Qwen2_5_VLForConditionalGeneration.from_pretrained(actor_path, torch_dtype=torch.bfloat16, attn_implementation="flash_attention_2",device_map="auto")
    processor = AutoProcessor.from_pretrained(actor_path, padding_side='left')
    return actor, processor

def generate_response_gpt4o(client, system_prompt="You are a helpful assistant.", user_prompt="", images=[]):
    """
    Single round conversation with GPT4o.
    Support system prompt, user prompt, and mutiple images.
    """
    assert len(system_prompt) > 0 or len(user_prompt) > 0, "At least one prompt must be provided"
    # Build content (user prompt + images)
    content = [{"type": "text", "text": user_prompt}]
    content = content + [
        {
            "type": "image_url",
            "image_url": {
                "url": f"data:image/png;base64,{base64.b64encode(open(image, 'rb').read()).decode('utf-8')}"
            }
        } for image in images
    ]
    # Build message
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": content}
    ]
    # Request
    for i in range(5):
        try:
            response = client.chat.completions.create(model="gpt-4o", messages=messages).choices[0].message.content
            return response
        except Exception as e:
            pass # Mutely retry
            # print(e)
        time.sleep(0.5)

def batch_inference_qwen25vl(actor, processor, messages):
    """
    Batch inference for Qwen2.5-VL
    """
    # Prepare inputs
    texts = [
        processor.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
        for msg in messages
    ]
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=texts,
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt"
    )
    inputs = inputs.to('cuda')
    # Inference
    generated_ids = actor.generate(**inputs, max_new_tokens=1024)
    generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_texts = processor.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True
    )
    return output_texts

def parallel_inference_gpt4o(args, proposals, round_idx):
    """
    Parallel inference for GPT4o.
    Input:
    - proposals: `List[Tuple[Dict, PIL.Image, Str]]` proposals generated by the Actor.
    - round_idx: `Tuple[Str, Int]` index of the round, e.g., ("Object", 1).
    """
    # Build GPT4o client
    AZURE_OPENAI_ENDPOINT = "https://safemo-gpt.openai.azure.com/"
    AZURE_OPENAI_API_KEY = "1d7dbbc5eeb4402a9a9de3df9b72d34b"
    client = AzureOpenAI(
        azure_endpoint=AZURE_OPENAI_ENDPOINT,
        api_key=AZURE_OPENAI_API_KEY,
        api_version="2023-03-15-preview"
    )
    # Select prompt template
    if round_idx[0] == "Object":
        system_prompt = OBJ_VERIFICATION["system"]
        user_prompt = OBJ_VERIFICATION["user"]
    elif round_idx[0] == "Part":
        system_prompt = PART_VERIFICATION["system"]
        user_prompt = PART_VERIFICATION["user"]
    # Parallel inference
    verfications = dict()
    with ThreadPoolExecutor(max_workers=10) as executor:
        future_to_image = {
            executor.submit(
                generate_response_gpt4o,
                client,
                system_prompt,
                user_prompt.format(
                    task=proposal[0]["input"]["task_description"],
                    proposal=proposal[2]
                ),
                [f"cot_tmp/{proposal[0]['input']['pre_contact_path'].split('/')[-1]}"]
            ): proposal[0]["input"]["pre_contact_path"]
            for proposal in proposals
        }
        for future in tqdm(as_completed(future_to_image), total=len(future_to_image), desc=f"Verification_GPT4o_{round_idx}"):
            image_path = future_to_image[future]
            try:
                response = future.result()
                verfications[os.path.basename(image_path)] = response
            except Exception as e:
                print(f"Error: {e}")
                verfications[os.path.basename(image_path)] = e
    # Log the verifications
    os.makedirs(os.path.join(args.logdir, args.exp_name, round_idx[0]), exist_ok=True)
    json.dump(
        verfications,
        open(os.path.join(args.logdir, args.exp_name, round_idx[0], f"Verification_GPT4o_{round_idx[1]}.json"), "w"),
        indent=4
    )
    return verfications
    
def initial_proposal(args, actor, processor, dataset, batch_size=8):
    """
    Initial proposal generation.
    `dataset` is a list of dictionaries, sub-sampling should be done before calling this function.
    """
    # Assemble messages
    messages = []
    for sample in tqdm(dataset, total=len(dataset), desc="Assembling messages for initial proposal"):
        image_path = sample["input"]["pre_contact_path"]
        message = [
            {"role": "system", "content": INITIAL_PROPOSAL["system"]},
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image_path},
                    {"type": "text", "text": INITIAL_PROPOSAL["user"].format(task=sample["input"]["task_description"])}
                ]
            }
        ]
        messages.append(message)
    # Batch inference
    proposals = []
    for i in tqdm(range(0, len(messages), batch_size), desc="Batch inference for initial proposal"):
        output_texts = batch_inference_qwen25vl(actor, processor, messages[i:i+batch_size])
        for output_text, message, sample in zip(output_texts, messages[i:i+batch_size], dataset[i:i+batch_size]):
            image = Image.open(sample["input"]["pre_contact_path"])
            input_width, input_height = image.size
            try:
                visualization, bbox = plot_bounding_boxes(image, output_text, input_width, input_height)
                proposals.append((sample, visualization, bbox))
            except Exception as e:
                print(f"Error: {e} for {sample['input']['pre_contact_path']}")
                proposals.append((sample, image, [0, 0, input_width, input_height]))
    # Log the proposals
    json.dump(
        {proposal[0]["input"]["pre_contact_path"].split("/")[-1]: proposal[2] for proposal in proposals},
        open(os.path.join(args.logdir, args.exp_name, "Initial_Proposal.json"), "w"),    
    )
    os.makedirs(os.path.join(args.logdir, args.exp_name, "Initial_Proposal"), exist_ok=True)
    for proposal in proposals:
        proposal[1].save(os.path.join(args.logdir, args.exp_name, "Initial_Proposal", proposal[0]["input"]["pre_contact_path"].split("/")[-1]))
    return proposals

def refine_proposal(args, actor, processor, proposals, verifications, round_idx, batch_size=8):
    """
    Proposal refinement.
    `proposals` is a list of tuples, each tuple is (sample, visualization, bbox).
    `verifications` is a dictionary, keys are image names, values are verifications.
    """
    # Assemble messages
    messages = []
    false_proposals = []
    for proposal in tqdm(proposals, total=len(proposals), desc="Assembling messages for proposal refinement"):
        image_path = proposal[0]["input"]["pre_contact_path"]
        verification = verifications[os.path.basename(image_path)]
        if verification is None or "Answer: Yes" in verification: # Skip the correct proposals
            continue
        message = [
            {"role": "system", "content": OBJ_REFINEMENT["system"]},
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image_path},
                    {"type": "text", "text": OBJ_REFINEMENT["user"].format(
                        bbox=proposal[2],
                        reason=verification.split("because")[1]
                    )}
                ]
            }
        ]
        messages.append(message)
        false_proposals.append(proposal)
    # Batch inference
    refined_proposals = []
    for i in tqdm(range(0, len(messages), batch_size), desc="Batch inference for proposal refinement"):
        output_texts = batch_inference_qwen25vl(actor, processor, messages[i:i+batch_size])
        for output_text, message, proposal in zip(output_texts, messages[i:i+batch_size], false_proposals[i:i+batch_size]):
            image = Image.open(proposal[0]["input"]["pre_contact_path"])
            input_width, input_height = image.size
            try:
                visualization, bbox = plot_bounding_boxes(image, output_text, input_width, input_height)
                refined_proposals.append((proposal[0], visualization, bbox))
            except Exception as e:
                print(f"Error: {e} for {proposal[0]['input']['pre_contact_path']}")
                refined_proposals.append((proposal[0], image, proposals[len(refined_proposals)][2]))
    # Log the refined proposals
    json.dump(
        {proposal[0]["input"]["pre_contact_path"].split("/")[-1]: proposal[2] for proposal in refined_proposals},
        open(os.path.join(args.logdir, args.exp_name, round_idx[0], f"Refined_Proposal_{round_idx[1]}.json"), "w"),    
    )
    os.makedirs(os.path.join(args.logdir, args.exp_name, round_idx[0], f"Refined_Proposal_{round_idx[1]}"), exist_ok=True)
    for proposal in refined_proposals:
        proposal[1].save(os.path.join(args.logdir, args.exp_name, round_idx[0], f"Refined_Proposal_{round_idx[1]}", proposal[0]["input"]["pre_contact_path"].split("/")[-1]))
    return refined_proposals

def main():
    args = parse_args()
    os.makedirs(os.path.join(args.logdir, args.exp_name), exist_ok=True)
    # Load the dataset
    dataset = json.load(open(args.data, "r"))
    # Downsample (Take the first sample for each noun-verb pair)
    dataset_downsampled = []
    for noun in dataset:
        for verb, samples in dataset[noun].items():
            for sample in samples:
                dataset_downsampled.append(sample)
                break
    # Build the actor
    actor, processor = build_actor(args.actor)
    # Initial proposal generation
    proposals = initial_proposal(args, actor, processor, dataset_downsampled)
    # Verification rounds
    for i in range(args.max_trails):
        print(f"########### Round {i} ###########")
        # Verification round
        verifications = parallel_inference_gpt4o(args, proposals, ("Object", i))
        # Refinement round
        proposals = refine_proposal(args, actor, processor, proposals, verifications, ("Object", i))
        
if __name__ == "__main__":
    main()